spring.application.name=MillenniumKiss
# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/feemanegment
spring.datasource.password=Gaikwadapeksha@2011

spring.datasource.username=root
#spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
#spring.datasource.password=yaBXqvQbiZIMQBmlEWhXLBRmoJopNVMy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework.web=DEBUG
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servers
server.port=8080